### PR TITLE
Move generic_response_for_service to a GenericHelper class

### PR DESCRIPTION
**Pull request by viniciuszago**
What do you think about to move the `generic_response_for_service` to a `GenericHelper` class, I think it make no sense to use UserHelper to share this method.

So instead of using this: 

```ruby
# helpers/users_helper.rb
module UsersHelper

  def response_for_user_create_service(service)
    success_response = { user: service.user, subscription: service.subscription }
    generic_response_for_service(service, success_response)
  end

  # THIS IS GREAT, you can use this method to standardize ALL of your
  # endpoints responses, THIS IS SO FUCKING COOL!
  def `(service, success_response)
    default_response = {
      status: service.response_status,
      status_code: service.response_status_code,
      success: service.success?
    }

    if service.success?
      response = success_response
    else
      response = {
        error: true,
        errors: service.errors
      }
    end

    default_response.merge(response)
  end
end
```

You could do something like:

```ruby
# helpers/generic_helper.rb
module GenericHelper

  def `(service, success_response)
    default_response = {
      status: service.response_status,
      status_code: service.response_status_code,
      success: service.success?
    }

    if service.success?
      response = success_response
    else
      response = {
        error: true,
        errors: service.errors
      }
    end

    default_response.merge(response)
  end

end
```

```ruby
# helpers/users_helper.rb
module UsersHelper

  def response_for_user_create_service(service)
    success_response = { user: service.user, subscription: service.subscription }
    generic_response_for_service(service, success_response)
  end

end
```

### CODE REVIEW

**Comment by fidelisrafael** [comment]
Vini, in this case is just a example of Rails application, in your code I recommend doing what you're saying...sharing the helpers "globally" e not only to an specific resource. But since we have this PR, I will accept it! But we need to include the `GenericHelpers` module in `UsersHelper`, can you send this modification?

``` ruby
module UsersHelper
  include GenericHelpers
end
```

**Comment by viniciuszago** [comment]
Cool!

**Comment by fidelisrafael** [comment]
@viniciuszago Now we need to update this branch to update the docs in [`docs/webframework_integrations.md`](https://github.com/fidelisrafael/nifty_services/blob/master/docs/webframeworks_integration.md#rails-) since this modification was directly in README.md before migrating to wiki.

**Comment by viniciuszago** [comment]
It's done

**Pull request merged**
