### PR TITLE
Setup travis and add build travis into README

### PR DESCRIPTION
**Pull request by lucasgomide**
@fidelisrafael You need turn on travis, before than accept this.

### CODE REVIEW

**Comment by fidelisrafael** [comment]
@lucasgomide Setup done! Github probably do a cache for static files in README, but tests are passing ;)

[Travis.ci](https://api.travis-ci.org/fidelisrafael/nifty_services)

Valeu!

**Comment by lucasgomide** [comment]
Your readme is with the svg with the wrong branch, it's only change it

**Comment by lucasgomide** [comment]
Sorry,i missing this :(

**Comment by fidelisrafael** [comment]
@lucasgomide You're right! I will update the README with the correct branch!

**Comment by fidelisrafael** [comment]
@lucasgomide done! Thanks again for submitting this!

**Comment by lucasgomide** [comment]
Noice :+1:

**Pull request merged**
